# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import bravia_control_pb2 as bravia__control__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in bravia_control_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ControlDeviceServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ConfirmSignin = channel.unary_unary(
                '/jp.co.sony.hes.ssh.controldevice.v1.ControlDeviceService/ConfirmSignin',
                request_serializer=bravia__control__pb2.ConfirmSigninRequest.SerializeToString,
                response_deserializer=bravia__control__pb2.ConfirmSigninResponse.FromString,
                _registered_method=True)
        self.ConfirmKeys = channel.unary_unary(
                '/jp.co.sony.hes.ssh.controldevice.v1.ControlDeviceService/ConfirmKeys',
                request_serializer=bravia__control__pb2.ConfirmKeysRequest.SerializeToString,
                response_deserializer=bravia__control__pb2.ConfirmKeysResponse.FromString,
                _registered_method=True)
        self.GetSessionRandom = channel.unary_unary(
                '/jp.co.sony.hes.ssh.controldevice.v1.ControlDeviceService/GetSessionRandom',
                request_serializer=bravia__control__pb2.GetSessionRandomRequest.SerializeToString,
                response_deserializer=bravia__control__pb2.GetSessionRandomResponse.FromString,
                _registered_method=True)


class ControlDeviceServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ConfirmSignin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConfirmKeys(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSessionRandom(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ControlDeviceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ConfirmSignin': grpc.unary_unary_rpc_method_handler(
                    servicer.ConfirmSignin,
                    request_deserializer=bravia__control__pb2.ConfirmSigninRequest.FromString,
                    response_serializer=bravia__control__pb2.ConfirmSigninResponse.SerializeToString,
            ),
            'ConfirmKeys': grpc.unary_unary_rpc_method_handler(
                    servicer.ConfirmKeys,
                    request_deserializer=bravia__control__pb2.ConfirmKeysRequest.FromString,
                    response_serializer=bravia__control__pb2.ConfirmKeysResponse.SerializeToString,
            ),
            'GetSessionRandom': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSessionRandom,
                    request_deserializer=bravia__control__pb2.GetSessionRandomRequest.FromString,
                    response_serializer=bravia__control__pb2.GetSessionRandomResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'jp.co.sony.hes.ssh.controldevice.v1.ControlDeviceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('jp.co.sony.hes.ssh.controldevice.v1.ControlDeviceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ControlDeviceService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ConfirmSignin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jp.co.sony.hes.ssh.controldevice.v1.ControlDeviceService/ConfirmSignin',
            bravia__control__pb2.ConfirmSigninRequest.SerializeToString,
            bravia__control__pb2.ConfirmSigninResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConfirmKeys(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jp.co.sony.hes.ssh.controldevice.v1.ControlDeviceService/ConfirmKeys',
            bravia__control__pb2.ConfirmKeysRequest.SerializeToString,
            bravia__control__pb2.ConfirmKeysResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSessionRandom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jp.co.sony.hes.ssh.controldevice.v1.ControlDeviceService/GetSessionRandom',
            bravia__control__pb2.GetSessionRandomRequest.SerializeToString,
            bravia__control__pb2.GetSessionRandomResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
