# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bravia_control.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'bravia_control.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




_pool = _descriptor_pool.DescriptorPool()
DESCRIPTOR = _pool.AddSerializedFile(b'\n\x14\x62ravia_control.proto\x12#jp.co.sony.hes.ssh.controldevice.v1\")\n\x14\x43onfirmSigninRequest\x12\x11\n\tauth_data\x18\x01 \x01(\x0c\"(\n\x15\x43onfirmSigninResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\":\n\x12\x43onfirmKeysRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x10\n\x08key_data\x18\x02 \x01(\x0c\"\x15\n\x13\x43onfirmKeysResponse\"-\n\x17GetSessionRandomRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\"Z\n\x18GetSessionRandomResponse\x12\x16\n\x0esession_random\x18\x01 \x01(\x0c\x12\x12\n\nauth_token\x18\x02 \x01(\x0c\x12\x12\n\nsession_id\x18\x03 \x01(\t\".\n\x18StartNotifyStatesRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t2\xb4\x03\n\x14\x43ontrolDeviceService\x12\x86\x01\n\rConfirmSignin\x12\x39.jp.co.sony.hes.ssh.controldevice.v1.ConfirmSigninRequest\x1a:.jp.co.sony.hes.ssh.controldevice.v1.ConfirmSigninResponse\x12\x80\x01\n\x0b\x43onfirmKeys\x12\x37.jp.co.sony.hes.ssh.controldevice.v1.ConfirmKeysRequest\x1a\x38.jp.co.sony.hes.ssh.controldevice.v1.ConfirmKeysResponse\x12\x8f\x01\n\x10GetSessionRandom\x12<.jp.co.sony.hes.ssh.controldevice.v1.GetSessionRandomRequest\x1a=.jp.co.sony.hes.ssh.controldevice.v1.GetSessionRandomResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bravia_control_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONFIRMSIGNINREQUEST']._serialized_start=61
  _globals['_CONFIRMSIGNINREQUEST']._serialized_end=102
  _globals['_CONFIRMSIGNINRESPONSE']._serialized_start=104
  _globals['_CONFIRMSIGNINRESPONSE']._serialized_end=144
  _globals['_CONFIRMKEYSREQUEST']._serialized_start=146
  _globals['_CONFIRMKEYSREQUEST']._serialized_end=204
  _globals['_CONFIRMKEYSRESPONSE']._serialized_start=206
  _globals['_CONFIRMKEYSRESPONSE']._serialized_end=227
  _globals['_GETSESSIONRANDOMREQUEST']._serialized_start=229
  _globals['_GETSESSIONRANDOMREQUEST']._serialized_end=274
  _globals['_GETSESSIONRANDOMRESPONSE']._serialized_start=276
  _globals['_GETSESSIONRANDOMRESPONSE']._serialized_end=366
  _globals['_STARTNOTIFYSTATESREQUEST']._serialized_start=368
  _globals['_STARTNOTIFYSTATESREQUEST']._serialized_end=414
  _globals['_CONTROLDEVICESERVICE']._serialized_start=417
  _globals['_CONTROLDEVICESERVICE']._serialized_end=853
# @@protoc_insertion_point(module_scope)
